# Generated by Django 5.2.3 on 2025-07-07 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0006_teamtasks_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtasks',
            name='assinged_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamtasks',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
