# Generated by Django 5.2.3 on 2025-07-12 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0013_remove_directs_user_directs_receiver_directs_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='directs',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myteam.directs'),
        ),
    ]
