# Generated by Django 5.2.3 on 2025-07-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0015_feed_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='sender',
            new_name='sender_user',
        ),
    ]
